### ISSUE TITLE
Config folder doesn't appear

### ISSUE THREAD

**Issue by Davonisgod** [Shirkie01/V2UnityDiscordIntercept#1]
Configs folder for BepinEx doesn't load after extraction, installed plugin with corresponding word size and went via troubleshooting procedures.
![Screenshot 2023-01-01 182924](https://user-images.githubusercontent.com/103961777/210187440-9842af40-822f-4cf3-a96c-2fa76862f783.png)

**Comment by Shirkie01** [comment]
The folders should be created the first time running the Vigilante2Unity
exe after extraction. Try running the game and closing it.

If that doesn't work, make sure you have the correct version of BepInEx. I
updated the link to point to version 6.0.0-pre.1. (x64, mono)

**Comment by Davonisgod** [comment]
Okay, I have the folders loaded and extracted, with discordinterceptor files extracted within configs folder. So, based from your cs, I assume when players joins the lobby, a window will pop up with insert boxes requesting the host's IP, port, and username??
![Screenshot 2023-01-02 194349](https://user-images.githubusercontent.com/103961777/210287696-3239ff69-c88e-484b-a065-fa3b75254b7f.png)
![Screenshot 2023-01-02 194514](https://user-images.githubusercontent.com/103961777/210287715-8b479fd5-edef-45f8-9d8d-1e2d6c3800b0.png)

**Comment by Shirkie01** [comment]
The `.dll` files should be located in the `plugins` folder. I've updated the readme to have a much more detailed description of the install and use.

**Comment by Davonisgod** [comment]
Also, what type do you suggest for IP address to be for matchmaking? static from ethernet adapter? translated from VPN? public from router?
![Screenshot 2023-01-02 215817](https://user-images.githubusercontent.com/103961777/210294875-a0cdb2d5-efcc-4e4b-8225-44ea6798b925.png)

**Comment by Shirkie01** [comment]
Any will work, it depends on your specific use case.

**Comment by Shirkie01** [comment]
Closing as resolved.
